                            <option value="0" selected disabled>Please Select</option>
                            <option value="36">36</option>
                            <option value="30">30</option>
                            <option value="26">26</option>
                            <option value="23">23</option>
                            <option value="22">22</option>
                            <option value="17.5">17.5</option>
                            <option value="16">16</option>
                            <option value="14.5">14.5</option>
                            <option value="12.25">12.25</option>
                            <option value="10.75">10.75</option>
                            <option value="9.875">9.875</option>
                            <option value="8.5">8.5</option>
                            <option value="6.75">6.75</option>
                            <option value="6.5">6.5</option>
                            <option value="6.25">6.25</option>
                            <option value="6">6</option>